### PR TITLE
Fix cursor issues

### LINKED ISSUE #7: Cursor starts in status window when run
image

### LINKED ISSUE #9: Right and bottom borders can be modified
I can move the cursor to the bottom and right borders of the canvas window and overwrite them.

### PR DESCRIPTION
**Pull request by labseven**
Fixes #9, fixes #7.

### CODE REVIEW

**Comment by newsch** [comment]
Closes #7, #9.

File: src/cursor.c [hunk 1]
```diff
@@ -21,7 +21,7 @@ void cursor_move_up(Cursor* cursor) {
 }
 
 void cursor_move_down(Cursor* cursor) {
-    if (cursor->y == (LINES - 2)) { // Take box lines into account
+    if (cursor->y == (LINES - 5)) { // Take box lines into account
```
Comment (newsch) [inline src/cursor.c:24]: These are to check against the border size and the status window size? Should those values be calculated and set in `frontend.c` or somewhere else?

**Comment by newsch** [comment]
I can confirm that it is fixed.

File: src/cursor.c (hunk 1 above)
Comment (newsch) [reply src/cursor.c:24]: Since @MatthewBeaudouinLafon won't have time to assess this I'll merge it in now. I added the issue as #24.

**Review by newsch — APPROVED** [review]
