### PR TITLE
fix writing canvas past bounds

### LINKED ISSUE #31: If the canvas is smaller than the terminal window, characters are still written

### PR DESCRIPTION
**Pull request by labseven**
It works nicely.
Also fixed not writing last line on the right and bottom.

fixes #31

### CODE REVIEW

File: src/frontend.c [hunk 1]
```diff
@@ -115,12 +115,26 @@ void front_setcharcursor(char ch) {
 }
 
 void redraw_canvas_win() {
-  for (int x = 0; x < view_max_x; x++) {
-    for (int y = 0; y < view_max_y; y++) {
+  int max_x = view_max_x;
```
Comment (newsch) [inline src/frontend.c:150]: These sections could be commented more.

File: src/cursor.c [hunk 2]
```diff
@@ -23,6 +23,9 @@ void cursor_move_up(Cursor *cursor, View *view) {
 }
 
 void cursor_move_down(Cursor *cursor, View *view) {
+  if (cursor->y == view->canvas->num_rows - view->y - 1){
```
Comment (newsch) [inline src/cursor.c]: I can't help but feel that checking for `==` instead of `>=`/`<=` will come back to bite us at some point, but it seems fine for now.

**Review by newsch — DISMISSED** [review]

**Comment by newsch** [comment]
I get a segfault when the canvas is too short, but not when it is too thin.

File: src/frontend.c [hunk 3]
```diff
@@ -115,12 +115,29 @@ void front_setcharcursor(char ch) {
...
+  for (int x = 0; x <= max_x; x++) {
+    for (int y = 0; y <= max_y; y++) {
       mvwaddch(canvas_win, y + 1, x + 1,
                canvas_gcharyx(view->canvas, y + view->y, x + view->x));
     }
   }
+
+  // draw fill in rest of window
+  for (int x = max_x; x < view_max_x; x++) {
+    for (int y = 0; y < view_max_y; y++) {
```
Comment (newsch) [inline src/frontend.c:168]: Should this be:
```suggestion
    for (int y = max_y; y < view_max_y; y++) {
```

File: src/frontend.c [hunk 4]
```diff
@@ -115,12 +115,29 @@ void front_setcharcursor(char ch) {
...
+  int max_y = view_max_y;
+
+  if (max_x > view->canvas->num_cols - view->x)
+    (max_x = view->canvas->num_cols - view->x);
+  if (max_y > view->canvas->num_rows - view->y)
+    (max_y = view->canvas->num_rows - view->y);
+
+  // draw canvas onto window
+  for (int x = 0; x <= max_x; x++) {
+    for (int y = 0; y <= max_y; y++) {
```
Comment (newsch) [inline src/frontend.c]: Starting at 0 and drawing at index +1 feels weird to me. Is this to get around the border width?

**Comment by labseven** [comment]
> I get a segfault when the canvas is too short, but not when it is too thin.

Fixed by messing with some magic numbers in `cursor` and `frontend`

File: src/frontend.c (hunk 4 above)
Comment (newsch) [reply src/frontend.c]: Or is this compensating for the window border?

**Comment by newsch** [comment]
I took a fresh look at it today. Starting with a view at (0, 0) and a canvas of size 10x10 I only get a usable space of 9x9:

```
┌──────────────────
│123456789XXXXXXXXX
│2        XXXXXXXXX
│3        XXXXXXXXX
│4        XXXXXXXXX
│5        XXXXXXXXX
│6        XXXXXXXXX
│7        XXXXXXXXX
│8        XXXXXXXXX
│9        XXXXXXXXX
│XXXXXXXXXXXXXXXXXX
│XXXXXXXXXXXXXXXXXX
│XXXXXXXXXXXXXXXXXX
│XXXXXXXXXXXXXXXXXX
```

**Comment by newsch** [comment]
Looks like it's overwriting the last row/column:

```
┌────────────
│0        XXX
│         XXX
│         XXX
│         XXX
│         XXX
│         XXX
│         XXX
│         XXX
│        8XXX
│XXXXXXXXXXXX
│XXXXXXXXXXXX
│XXXXXXXXXXXX
```

To replicate:
```patch
diff --git a/src/frontend.c b/src/frontend.c
index 17fc043..e592c2a 100644
--- a/src/frontend.c
+++ b/src/frontend.c
@@ -51,9 +51,12 @@ int main(int argc, char *argv[]) {
   status_win = create_status_win();
 
   cursor = cursor_new();
-  Canvas *canvas = canvas_new_blank(1000, 1000);
+  Canvas *canvas = canvas_new_blank(10, 10);
+  canvas_scharyx(canvas, 0, 0, '0');
+  canvas_scharyx(canvas, 8, 8, '8');
+  canvas_scharyx(canvas, 9, 9, '9');
 
-  view = view_new_startpos(canvas, 300, 300);
+  view = view_new_startpos(canvas, 0, 0);
 
   // Enable keyboard mapping
   keypad(canvas_win, TRUE);
@@ -71,7 +74,7 @@ int main(int argc, char *argv[]) {
   State new_state = {
       .ch_in = 0,
       .cursor = cursor,
-      .current_mode = MODE_INSERT,
+      .current_mode = MODE_PAN,
       .last_arrow_direction = KEY_RIGHT,
       .last_canvas_mode = MODE_INSERT,
       .view = view,
```

**Comment by labseven** [comment]
Yes I know my off-by-ones are messy. I'll clean it up today.

**Comment by newsch** [comment]
I got it working in 5253be5 but it doesn't draw to the edge of the screen anymore. I think I have a fix almost done.

**Comment by newsch** [comment]
Another bug I found was panning the screen past the end of the canvas overwrites the border.

**Comment by labseven** [comment]
Ok, I cleaned it up and added bounds checking

**Comment by labseven** [comment]
I fixed the "panning the screen past the end of the canvas overwrites the border." by checking for panning bounds. It will not let you pan past the edge anymore.

**Comment by newsch** [comment]
Looks good, but now the cursor can move to the bottom and right border again.
What are `view_max_x` and `view_max_y` supposed to represent?

**Comment by labseven** [comment]
darn it. Let me dig deeper

**Review by newsch — APPROVED** [review]
Works for me. Do you want to rebase before merging it in?

**Comment by newsch** [comment]
Looks like that had some duplicates of `free-line`. I don't think that will cause us any issues though.
